# Generated by Django 6.0.3 on 2026-04-01 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('table', 'Столик'), ('event', 'Мероприятие'), ('other', 'Другое')], default='table', max_length=20, verbose_name='Тип бронирования')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('booking_time', models.TimeField(verbose_name='Время бронирования')),
                ('number_of_persons', models.PositiveIntegerField(verbose_name='Количество человек')),
                ('table_number', models.CharField(blank=True, max_length=50, verbose_name='Столик')),
                ('name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Ожидается подтверждение'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Выполнено')], default='pending', max_length=20, verbose_name='Статус')),
                ('special_requests', models.TextField(blank=True, verbose_name='Специальные пожелания')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
